print('Enter the name of cat 1:')
catName1 = input()
print('Enter the name of cat2:')
catName2 = input()
print('Enter the name of cat3:')
catName3 = input()
print('Enter the name of cat4:')
catName4 = input()
print('Enter the name of cat5:')
catName5 = input()
print('Enter the name of cat6')
catName6 = input()
print(f"{catName1} {catName2} {catName3} {catName4} {catName5} {catName6}")
